language: node_js
node_js:
  - 0.12
  - 4
  - node
install: npm install
script: npm test
after_success: npm run coverage && cat ./coverage/lcov.info | coveralls
notifications:
  webhooks: http://webhook.hakatashi.com/travis
